apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: secret-management-operator
    app.kubernetes.io/managed-by: kustomize
  name: leader-election-rolebinding
  namespace: secret-management-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: secret-management-operator-system
