# permissions for end users to edit openbaoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: secret-management-operator
    app.kubernetes.io/managed-by: kustomize
  name: openbao-editor-role
rules:
- apiGroups:
  - instance.secrets.com
  resources:
  - openbaoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - instance.secrets.com
  resources:
  - openbaoes/status
  verbs:
  - get
- apiGroups: [""]
  resources:
    - configmaps
  verbs:
    - get
    - list
    - watch
