# permissions for end users to view openbaoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: secret-management-operator
    app.kubernetes.io/managed-by: kustomize
  name: openbao-viewer-role
rules:
- apiGroups:
  - instance.secrets.com
  resources:
  - openbaoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - instance.secrets.com
  resources:
  - openbaoes/status
  verbs:
  - get
