name: Build and Push Docker Image on Release

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write  # Gir nødvendig tilgang til GHCR

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v4  # Sørger for at repoet lastes ned

      - name: Logg inn i GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bygg og push Docker-image
        uses: docker/build-push-action@v5
        with:
          context: .  # Endre til ./docker hvis Dockerfile ligger i en undermappe
          file: ./Dockerfile  # Endre hvis filnavnet er annerledes
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
